#!/usr/bin/env node
/*
 * Regenerate THIRD_PARTY_NOTICES.md from vendor/sources.json.
 *
 * The closure test fails closed when a vendored file is missing
 * from the notices; this script keeps the table in lock-step with
 * the manifest produced by vendor-sync.mjs.
 */

import { writeFile, readFile } from "node:fs/promises";
import { resolve, join } from "node:path";
import { fileURLToPath } from "node:url";
import { dirname } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO = resolve(__dirname, "..");
const MANIFEST_PATH = join(REPO, "vendor", "sources.json");
const NOTICES_PATH = join(REPO, "THIRD_PARTY_NOTICES.md");

const manifest = JSON.parse(await readFile(MANIFEST_PATH, "utf8"));
const sorted = [...manifest.sources].sort((a, b) => a.localTarget.localeCompare(b.localTarget));

const header = `# Third-Party Notices

\`opencode-ship@1.0.0\` ships the complete Matt Pocock and Superpowers
methodology under the MIT license, plus the Ship-owned installer,
plugin, agents, and skills. The complete immutable pin list is in
\`vendor/sources.json\`; the upstream snapshots are under
\`vendor/upstreams/<owner>/\`. The canonical MIT text for each
upstream is preserved in \`vendor/<owner>/LICENSE\`.

The engineering profile is the consumer-installable bundle of
all 24 vendored skills (14 mattpocock + 10 obra/superpowers)
plus the Ship-owned delivery agents, plugin, and Plan Mode
permission block.

## Bundled skill content

Every vendored file is recorded in \`vendor/sources.json\` with its
sourceRef, upstream SHA-256, and local SHA-256. The complete list
is generated by \`node scripts/vendor-sync.mjs\`; the table below
shows the engineering-profile skill SKILL.md files plus their
accompanying companion files (templates, prompt files, and ADR
helpers shipped verbatim from upstream under MIT).

| Profile | Local file | Upstream repo | License | Reuse mode |
|---|---|---|---|---|
`;

const rows = sorted.map((s) => {
  const repoShort = s.repository.split("/")[0];
  const licenseOwner = repoShort === "mattpocock" ? "mattpocock" : "superpowers";
  return `| engineering | \`${s.localTarget}\` | \`${s.repository}\` | MIT (see \`vendor/${licenseOwner}/LICENSE\`) | ${s.reuseMode} |`;
}).join("\n");

const footer = `
`;

await writeFile(NOTICES_PATH, header + rows + footer, "utf8");
console.error(`wrote ${sorted.length} rows to THIRD_PARTY_NOTICES.md`);