/*
 * Install fixture: build a minimal Git repository with optional
 * legacy shapes so the CLI tests have a deterministic starting point.
 */

import { spawnSync } from "node:child_process";
import { mkdtemp, writeFile, mkdir, rm, symlink, utimes } from "node:fs/promises";
import { existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { writeFile as fsWriteFile } from "node:fs/promises";

async function git(repoRoot, args, env) {
  const r = spawnSync("git", ["-C", repoRoot, ...args], {
    env: { ...process.env, ...(env ?? {}) },
    encoding: "utf8",
  });
  return { status: r.status ?? -1, stdout: r.stdout ?? "", stderr: r.stderr ?? "" };
}

export function gitCmd(repoRoot, args, env) {
  return git(repoRoot, args, env);
}

export async function makeProject({ packageManager = "pnpm", scripts = {}, withOrigin = true, sha = "abc123" } = {}) {
  const parent = await mkdtemp(join(tmpdir(), "opencode-ship-fixture-"));
  const repoRoot = join(parent, "proj");
  await mkdir(repoRoot, { recursive: true });
  await git(repoRoot, ["init", "--quiet", "--initial-branch", "main"], { GIT_AUTHOR_NAME: "test", GIT_AUTHOR_EMAIL: "test@example.com" });
  await git(repoRoot, ["config", "user.name", "fixture"], { GIT_AUTHOR_NAME: "test", GIT_AUTHOR_EMAIL: "test@example.com" });
  await git(repoRoot, ["config", "user.email", "fixture@example.com"], { GIT_AUTHOR_NAME: "test", GIT_AUTHOR_EMAIL: "test@example.com" });
  await writeFile(join(repoRoot, "package.json"), JSON.stringify({
    name: "fixture",
    version: "0.0.0",
    private: true,
    scripts: {
      verify: "node -e \"console.log('ok')\"",
      typecheck: "node -e \"console.log('ok')\"",
      ...scripts,
    },
  }, null, 2));
  if (packageManager === "pnpm") {
    await writeFile(join(repoRoot, "pnpm-lock.yaml"), "lockfileVersion: '6.0'\n");
  } else if (packageManager === "yarn") {
    await writeFile(join(repoRoot, "yarn.lock"), "# This file is generated by running yarn install.\n");
  } else if (packageManager === "npm") {
    await writeFile(join(repoRoot, "package-lock.json"), "{}\n");
  }
  await writeFile(join(repoRoot, "README.md"), "# fixture\n");
  await git(repoRoot, ["add", "."], { GIT_AUTHOR_NAME: "test", GIT_AUTHOR_EMAIL: "test@example.com" });
  await git(repoRoot, ["commit", "-m", "initial", "--no-gpg-sign"], { GIT_AUTHOR_NAME: "test", GIT_AUTHOR_EMAIL: "test@example.com" });
  if (withOrigin) {
    // local origin remote pointing at self for slug detection; the
    // runner doesn't actually fetch.
    await git(repoRoot, ["remote", "add", "origin", `git@github.com:Viktorxyz/fixture.git`], { GIT_AUTHOR_NAME: "test", GIT_AUTHOR_EMAIL: "test@example.com" });
  }
  return { parent, repoRoot, sha };
}

export async function cleanProject(parent) {
  await rm(parent, { recursive: true, force: true });
}

export async function writeFileTo(repoRoot, rel, contents) {
  const path = join(repoRoot, rel);
  await mkdir(path.split("/").slice(0, -1).join("/"), { recursive: true });
  await writeFile(path, contents);
  return path;
}

export async function exists(p) {
  return existsSync(p);
}

export async function touchWithMtime(path, mtime) {
  await utimes(path, mtime, mtime);
}

export async function makeSymlink(target, linkPath) {
  await mkdir(linkPath.split("/").slice(0, -1).join("/"), { recursive: true });
  try { await rm(linkPath); } catch { /* noop */ }
  await symlink(target, linkPath);
}

void fsWriteFile;
